sudo: required   # gives super user level permissions

services:
  - docker       # install a copy of docker

before_install:
  - docker build -t aloneinabyss/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true aloneinabyss/docker-react-course npm run test
