language: node_js
os: linux
dist: alpine

services:
  - docker       # install a copy of docker

before_install:
  - docker build -t aloneinabyss/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true aloneinabyss/docker-react-course npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket: "elasticbeanstalk-sa-east-1-421289294484"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"